version: 2
jobs:
  build:
    machine: true
    environment:
      TAG: 1.0.0
    steps:
      - checkout
      - run:
          name: Build Image
          command: |
            docker build -t ismaleiva90/sandbox:$TAG .
      - run:
          name: Test Image
          command: |
            docker run -it ismaleiva90/sandbox:$TAG node -v
            docker run -it ismaleiva90/sandbox:$TAG npm -v
            docker run -it ismaleiva90/sandbox:$TAG pip --version
  deploy:
    machine: true
    environment:
      TAG: 1.0.0
    steps:
      - checkout
      - run:
          name: Build Image
          command: |
            docker build -t ismaleiva90/sandbox:$TAG .
            docker build -t ismaleiva90/sandbox:latest .
      - run:
          name: Deploy if tests pass and branch is Master
          command: |
            docker login -u ismaleiva90 -p ${REGISTRY_PASS}
            docker push ismaleiva90/sandbox:$TAG
            docker push ismaleiva90/sandbox:latest

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

